site_name: MZmine 3 Documentation
site_url: https://mzmine.github.io/mzmine_documentation/
edit_uri: https://github.com/mzmine/mzmine_documentation/edit/master/docs/
repo_name: mzmine/mzmine_documentation
repo_url: https://github.com/mzmine/mzmine_documentation

nav:
  - Home page: index.md
  - Main window overview: Main-window-overview.md
  - LC-MS workflow: wf_featuredetection/lcms-workflow.md
  - LC-IMS-MS workflow: wf_featuredetection/Ion-mobility-data-processing-workflow.md
  - Module documentations:
      - Data import: wf_featuredetection/data-import.md
      - Mass detection: wf_featuredetection/mass-detection.md
      - Mobility scan merging: wf_featuredetection/mobility-scan-merging.md
      - ADAP Chromatogram builder: wf_featuredetection/adap-chromatogram-builder.md
      - Ion mobility expander: wf_featuredetection/ims-expander.md
      - Ion mobility trace builder: wf_featuredetection/ion-mobility-trace-builder.md
      - Smoothing: wf_featuredetection/smoothing.md
      - Resolving: wf_featuredetection/local-minimum-resolver.md
      - CCS calibration: module_docs/ccs_calibration.md
  - Visualisation:
      - Raw data visualisation: Raw-data-visualisation.md
  - Performance options: performance.md
  - Contribute: Contribute.md
  - Acknowledgements: wikiacknowledgements.md

theme:
  name: material

plugins:
  - search
  - git-authors:
      show_contribution: true
  - git-revision-date-localized:
      type: datetime

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
