site_name: MZmine 3 Documentation
site_url: https://mzmine.github.io/mzmine_documentation/
edit_uri: https://github.com/mzmine/mzmine_documentation/edit/master/docs/
repo_name: mzmine/mzmine_documentation
repo_url: https://github.com/mzmine/mzmine_documentation
use_directory_urls: false

nav:
  - Home page: index.md
  - Getting started: getting_started.md
  - Main window overview: main-window-overview.md
  
  - Visualisation modules:
      - Raw data visualisation: visualization_modules/raw-data-visualisation.md
      - Ion mobility data visualisation:  visualization_modules/ims_raw_data_overview/IM-data-visualisation.md
      - MSMS Visualizer: visualization_modules/msmsplot/msms-plot.md
  
  - Processing modules:
      - Data import: module_docs/io/raw_data_import/data-import.md
      - Mass detection:
        - Mass detection: module_docs/featdet_mass_detection/mass-detection.md
        - Mass detection algorithms: module_docs/featdet_mass_detection/mass-detection-algorithms.md
      - Mobility scan merging: module_docs/featdet_mobility_scan_merging/mobility-scan-merging.md
      - ADAP Chromatogram builder: module_docs/featdet_adap_chromatogram_builder/adap-chromatogram-builder.md
      - Ion mobility expander: module_docs/featdet_ims_expander/ims-expander.md
      - Ion mobility trace builder: module_docs/featdet_ion_mobility_trace_builder/ion-mobility-trace-builder.md
      - Smoothing: module_docs/featdet_smoothing/smoothing.md
      - Resolving: module_docs/featdet_resolver_local_minimum/local-minimum-resolver.md
      - CCS calibration: module_docs/id_ccs_calibration/ccs_calibration.md
      - Gap filling (Peak finder): module_docs/gapfill_peak_finder/gap-filling.md
      - MS2 scan paring: module_docs/featdet_ms2_scan_pairing/ms2_scan_pairing.md
      - 13C isotope filter (isotope grouper): module_docs/filter_isotope_filter/isotope_filter.md 
      - Isotope pattern finder: module_docs/filter_isotope_finder/isotope_finder.md 
      - Export to GNPS-FBMN/IIMN: module_docs/GNPS_export/gnps_export.md
  - Workflows:
      - LC-MS workflow: workflows/lcmsworkflow/lcms-workflow.md
      - LC-IMS-MS workflow: workflows/imsworkflow/ion-mobility-data-processing-workflow.md
      - Batch processing: workflows/batch_processing/batch-processing.md 
  - Visualisation:
      - Raw data visualisation: visualization_modules/raw-data-visualisation.md
      - Ion mobility data visualisation:  visualization_modules/ims_raw_data_overview/IM-data-visualisation.md
      - MSMS Visualizer: visualization_modules/msmsplot/msms-plot.md
  - Additional resources:
      - Gerneral Terminology: terminology/general-terminology.md
      - IMS Terminology: terminology/ion-mobility-terminology.md
      - IMS data format insight: workflows/imsworkflow/lc-ms-and-lc-ims-ms-data-comparison.md
      
  - Performance options: performance.md
  - Command line tool (batch mode): commandline_tool.md
  - Contribute: contribute.md
  - Acknowledgements: wikiacknowledgements.md

theme:
  name: material
  logo: img/MZMine_logo_white.png

plugins:
  - search
  - git-authors:
      show_contribution: true
  - git-revision-date-localized:
      type: datetime
  - with-pdf:
      output_path: documentation.pdf
      author: The MZmine Community
      cover_title: MZmine 3
      cover_subtitle: Documentation
      cover_logo: img/MZmine_logo_CMYK.png

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  # https://squidfunk.github.io/mkdocs-material/reference/formatting/
  # superscript ^13^C subscript H~2~O
  # key combinations: ++ctrl+alt+del++
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
