site_name: mzmine documentation
site_url: https://mzmine.github.io/mzmine_documentation/
edit_uri: https://github.com/mzmine/mzmine_documentation/edit/master/docs/
repo_name: mzmine/mzmine_documentation
repo_url: https://github.com/mzmine/mzmine_documentation
use_directory_urls: false

nav:
  - Home page: index.md
  - Getting started: getting_started.md
  - User account: services/users.md
  - Learners corner: learners_corner.md
  - Main window overview: main-window-overview.md
  - Processing wizard: wizard.md
  - Data conversion: data_conversion.md
  - Performance options: performance.md
  - Command line tool (batch mode): commandline_tool.md
  - Integration to other tools: tool_integration.md
  #  - Citations: citations.md

  - Processing modules:
      - I/O:
          - Raw data import: module_docs/io/data-import.md
          - Raw data export: module_docs/io/data-export.md
          - Feature list import: module_docs/io/feat-list-import.md
          - Feature list export: module_docs/io/feat-list-export.md
          - Export to other software: module_docs/io/data-exchange-with-other-software.md
          - Spectral library export: module_docs/io_spectral_library_export/spectral_library_generation.md
          - Export scans (feature list): module_docs/io_scans_feature/export-scans-feature.md
          - Export MRM to TSV: module_docs/io_mrmtotsv/mrm-to-tsv.md
          - Export feature data: module_docs/io_export_feature_data/export-feature-data.md
          - Annotation graphics export: module_docs/io_annotationgraphics/export_annotation_graphics.md
      #         TODO Add feature list import/export
      - File merging:
          - Raw data files merging: module_docs/featdet_file_merging/raw-files-merging.md
          - Mobility scan merging: module_docs/featdet_mobility_scan_merging/mobility-scan-merging.md
      - Raw data filtering:
          - Scan by scan filtering: module_docs/filter_raw_data/filter-scan-by-scan.md
          - Crop filter: module_docs/filter_raw_data/crop-filter.md
          - Baseline corrections: module_docs/filter_raw_data/baseline-corrections.md
          - Align scans: module_docs/filter_raw_data/align-scans.md
          - Scan smoothing: module_docs/filter_raw_data/scan_smoothing.md
      - Mass detection:
          - Mass detection: module_docs/featdet_mass_detection/mass-detection.md
          - Mass detection algorithms: module_docs/featdet_mass_detection/mass-detection-algorithms.md
          - FTMS shoulder peak finder: module_docs/featdet_mass_detection/FTMS-shoulder-peak-filter.md
          - Mass calibration: module_docs/featdet_mass_detection/mass-calibration.md
      - LC-MS feature detection:
          - Chromatogram builder: module_docs/lc-ms_featdet/featdet_adap_chromatogram_builder/adap-chromatogram-builder.md
          - MSn tree builder: module_docs/featuredet_msn_tree/msn_tree_builder.md
          - GridMass: module_docs/lc-ms_featdet/featdet_gridmass/gridmass.md
          - Targeted feature detection: module_docs/lc-ms_featdet/targeted_featdet/targeted-featdet.md
          - Feature detection results: module_docs/lc-ms_featdet/featdet_results/featdet_results.md
      - LC-IMS-MS feature detection:
          #       TODO Rework this one
          - Ion mobility expander: module_docs/lc-ims-ms_featdet/featdet_ims_expander/ims-expander.md
          - Ion mobility trace builder: module_docs/lc-ims-ms_featdet/featdet_ion_mobility_trace_builder/ion-mobility-trace-builder.md
          - Recursive IMS builder: module_docs/lc-ims-ms_featdet/recursive_ims_builder/recursive-ims-builder.md
      - MS imaging feature detection:
          - Image builder: module_docs/imaging_featdet/featdet_image_builder/image-builder.md
      - MRM feature detection:
          - MRM to Scans: module_docs/mrm_mrmtoscans/mrm-to-scans.md
          - Set MRM quantifiers: module_docs/mrm_setquant/mrm-set-quant-mass.md
      - Smoothing: module_docs/featdet_smoothing/smoothing.md
      - Resolving:
          - Local minimum resolver: module_docs/featdet_resolver_local_minimum/local-minimum-resolver.md
          - ADAP resolver: module_docs/featdet_resolver_adap/adap-resolver.md
          - Baseline resolver: module_docs/featdet_resolver_baseline/baseline-resolver.md
          - CentWave resolver: module_docs/featdet_resolver_centwave/centwave-resolver.md
          - Noise amplitude resolver: module_docs/featdet_resolver_noise_ampl/noise-ampl-resolver.md
          - Savitzky-Golay resolver: module_docs/featdet_resolver_savitzky-golay/savitzky-golay-resolver.md
      #      TODO Add mobilogram binning
      - Spectral deconvolution (GC):
          - GC-EI spectral deconvolution: module_docs/featdet_spectraldeconvolutiongc/spectraldeconvolutiongc.md
          #- Hierarchical clustering: module_docs/featdet_hierarch_clustering/featdet_hierarch_clustering.md
          #- Multivariate curve resolution: module_docs/featdet_multivariate_curve_res/featdet_multivar_curve_res.md
      - CCS calibration: module_docs/id_ccs_calibration/ccs_calibration.md
      - MS2 scan pairing: module_docs/featdet_ms2_scan_pairing/ms2_scan_pairing.md
      - MALDI MS2 scan pairing (SIMSEF): module_docs/featdet_ms2_scan_pairing/ms2_maldi_scan_pairing.md
      - Isotope filtering:
          - 13C isotope filter (isotope grouper): module_docs/filter_isotope_filter/isotope_filter.md
          - Isotope pattern finder: module_docs/filter_isotope_finder/isotope_finder.md
          - Isotope peak scanner: module_docs/filter_isotope_peak_scanner/isotope_peak_scanner.md
      - Feature grouping:
          - Correlation grouping: module_docs/id_ion_networking/metacorr/metacorr.md
          - Ion Identity Networking: module_docs/id_ion_networking/iin/iin.md
          - Spectral / Molecular Networking: module_docs/group_spectral_net/molecular_networking.md
      - Feature list filtering:
          - Duplicate feature filter: module_docs/filter_duplicate_features/duplicate_feature_filter.md
          - Feature list rows filter: module_docs/feature_list_row_filter/feature_list_rows_filter.md
          - Feature filter: module_docs/feature_filter/feature_filter.md
          - Peak comparison rows filter: module_docs/filter_peakcomparison_row_filter/filter_peakcomparison_row_filter.md
          - Neutral loss filter: module_docs/filter_neutral_loss/filter_neutral_loss.md
          - m/z mobility region extraction: module_docs/filter_mobilitymzregionextraction/filter_mobilitymzregionextraction.md
          - Feature list blank subtraction: module_docs/filter_blanksubtraction/filter_blanksubtraction.md
      - Alignment:
          - Join aligner: module_docs/align_join_aligner/join_aligner.md
          - Merge lists: module_docs/align_merge_lists/align_merge_lists.md
          - RANSAC aligner: module_docs/align_ransac/align_ransac.md
          #          - Hierachical aligner (GC): module_docs/align_hierarch/align_hierarch.md
          #          - ADAP aligner (GC): module_docs/align_adap/align_adap_gc.md
          - GC-EI aligner: module_docs/align_gcei/align_gc_ei.md
          - LC Image Aligner: module_docs/align_lc-image/align_lc-image.md
          - MRM aligner: module_docs/align_mrm/mrm-aligner.md
      - Gap filling:
          - Peak finder: module_docs/gapfill_peak_finder/gap-filling.md
          - Same RT and m/z range gap filler: module_docs/gapfill_same_mz_and_RT_range/same_mz_and_RT_range_gap_filler.md
      - Normalization:
          - Retention time calibration: module_docs/norm_rt_calibration/norm_rt_calibration.md
          - Linear normalizer: module_docs/norm_linear/norm_linear.md
          - Standard compound normalizer: module_docs/norm_stand_cmpd/norm_stand_cmpd.md
          - Retention index calculation: module_docs/norm_ri/norm_ri.md
      #      TODO decide what to do with spectral lib creation
      #  - Spectral library creation: module_docs/id_spectral_library_creation/spectral_library_creation.md
      - Precursor mass search:
          - Local database search: module_docs/id_prec_local_cmpd_db/local-cmpd-db-search.md
          - Precursor search in local spectral MS/MS library: module_docs/id_prec_local_spectra_lib/local-spectra-lib-search.md
      - Spectra search:
          - Spectral library search: module_docs/id_spectral_library_search/spectral_library_search.md
          - NIST MS search: module_docs/id_spectra_NIST/NIST-ms-search.md
          - Chemical formula prediction: module_docs/id_spectra_chem_formula/chem-formula-pred.md
          - Lipid annotation: module_docs/id_lipid_annotation/lipid-annotation.md
          - MS2 similarity search: module_docs/id_ms2_similarity/ms2-similarity-search.md
      - Other parameters:
          - Merge & select fragment scans: module_docs/filter_scan_merge_select/scan_merge_select.md
          - Spectra similarity: module_docs/align_join_aligner/spectra_similarity.md
      - Other detectors (UV):
          - Chromatogram builder (Other spectral data): module_docs/uv/uv_spectra_chromatogram_builder/spectrachrombuilder.md
          - Shift, trim, and bin traces (Other detectors): module_docs/uv/uv_shift_trim_bin_traces/uv_shift_trim_bin_traces.md
          - Baseline correction (Other detectors): module_docs/uv/uv_baseline_correction/uv_baseline_correction.md
          - Local minimum resolver (Other detectors): module_docs/uv/uv_resolve_traces/uv_local_min_resolver.md
          - Correlate MS features with other detectors: module_docs/uv/uv_ms_other_aligner/uv_ms_other_aligner.md

  - Visualization modules:
      - Visualization overview: visualization_modules/visualization_overview/visualization-overview.md
      - MS data visualisation:
          - Raw data overview: visualization_modules/raw_data_overview/raw_data_overview.md
          - Additional tools: visualization_modules/raw_data_overview/raw_data_additional.md
      - Ion mobility data visualisation: visualization_modules/ims_raw_data_overview/IM-data-visualisation.md
      - Image viewer: visualization_modules/image_raw_data/image_viewer.md
      - Image co-localization: module_docs/group_imagecorrelate/image-colocalization.md
      - Processed data visualization:
          - MSMS Visualizer: visualization_modules/msmsplot/msms-plot.md
          - Interactive Ion Identity Molecular Networks: visualization_modules/interactive_ion_id_netw/interactive_ion_id_netw.md
          - Feature histograms: visualization_modules/feature_histograms/feature_hist.md
          - 4D features plot (Kendrick): visualization_modules/kendrickmass/kendrick_mass_plot.md
          - Van Krevelen plot: visualization_modules/vankrevelen/van_krevelen_plot.md
          - ECN (Equivalent Carbon Number) models: visualization_modules/ecn_plots/ecn_plots.md
          - Lipid annotation summary: visualization_modules/lipid_annotation_summary/lipid_annotation_summary.md
          - Additional tools: visualization_modules/processed_additional/processed_additional.md
      - Massvoltammogram: visualization_modules/massvoltammogram/massvoltammogram.md
      - Statistics dashboard: visualization_modules/statistics_dashboard/statistics_dashboard.md
      - Multi detector visualizer: module_docs/uv/uv_multi_detector_visualizer/uv_multi_detector_visualizer.md
      - Correlation dashboard: module_docs/uv/uv_correlation_dashboard/uv_correlation_dashboard.md

  - Workflows:
      - Untargeted LC-MS workflow: workflows/lcmsworkflow/lcms-workflow.md
      - Untargeted LC-IMS-MS workflow: workflows/imsworkflow/ion-mobility-data-processing-workflow.md
      - Untargeted GC-MS workflow: workflows/gcmsworkflow/gcms-workflow.md
      - Untargeted MS imaging workflow: workflows/imagingworkflow/imaging-workflow.md
      - Batch processing: workflows/batch_processing/batch-processing.md
      - Library generation: workflows/librarygeneration/library_generation.md
      - SIMSEF: workflows/simsef/simsef_workflow.md
      - MRM workflow: workflows/mrmworkflow/mrm-workflow.md
      - Workflow optimization: workflows/optimization/workflow_optimization.md

  - Tools:
      - SIMSEF scheduler: module_docs/tools_simsef/simsef.md

  - Additional resources:
      - System requirements: system_requirements.md
      - General Terminology: terminology/general-terminology.md
      - IMS Terminology: terminology/ion-mobility-terminology.md
      - LC-MS and LC-IMS-MS data comparison: workflows/imsworkflow/lc-ms-and-lc-ims-ms-data-comparison.md
      #      - Kendrick mass defect: module_docs/feature_list_row_filter/kendrick_mass_defect.md
      - Spectral similarity measures: module_docs/id_spectral_library_search/spectral-similarity-measures.md
      - Other detector terminology: module_docs/uv/otherdetector_glossary.md

  - Contribute:
      - Coding:
          - mzmine development (in IntelliJ): contribute_intellij.md
          - Upgrade JDK version: coding/upgrade_jdk_version.md
          - General structure: coding/general_structure.md
          #            - macOS code signing: coding/macos_signing.md
          - Module development: coding/module_development.md
          - Modules list: coding/module_list.md

      #            TODO Finish writing these
      #            - Raw data structure: coding/raw_data_structure.md
      #            - Feature data structure: coding/feature_data_structure.md
      #            - Example module - Spectral entropy: coding/example_module.md
      - Contribute to documentation: contribute.md
      - Documentation template: contribute_docu_template.md

  - Acknowledgements: wikiacknowledgements.md
  - Troubleshooting: troubleshooting.md
  - Changelog: changelog.md
  - Workshops: workshops.md


copyright: This documentation is licensed under the MIT License (MIT).

extra_css:
  - css/extra.css

theme:
  name: material
  logo: img/mzmine_logo_white.png
  palette:
    scheme: default
    primary: custom

plugins:
  - search
  - git-authors:
      show_contribution: false
  - git-revision-date-localized:
      type: datetime
  - with-pdf:
      output_path: documentation.pdf
      author: The mzmine Community
      cover_title: mzmine
      cover_subtitle: Documentation
      cover_logo: docs/img/mzmine_logo_CMYK.png

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  #   https://squidfunk.github.io/mkdocs-material/reference/formatting/
  #   superscript ^13^C subscript H~2~O
  #   key combinations: ++ctrl+alt+del++
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
